; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.35"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.7"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[entitycache][subdir] = "contrib"
projects[entitycache][version] = "1.2"

projects[features][subdir] = "contrib"
projects[features][version] = "2.4"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta8"

projects[media][subdir] = "contrib"
projects[media][version] = "1.4"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.5"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[shib_auth][subdir] = "contrib"
projects[shib_auth][version] = "4.1"

projects[simplehtmldom][subdir] = "contrib"
projects[simplehtmldom][version] = "1.12"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[views][subdir] = "contrib"
projects[views][version] = "3.10"

; Custom Modules

projects[bhutan][type] = "module"
projects[bhutan][download][type] = "git"
projects[bhutan][download][url] = "https://github.com/shanti-uva/drupal_bhutan_modules.git"

projects[kmaps_modules][type] = "module"
projects[kmaps_modules][download][type] = "git"
projects[kmaps_modules][download][url] = "https://github.com/shanti-uva/drupal_kmaps_modules.git"

projects[sarvaka_modules][type] = "module"
projects[sarvaka_modules][download][type] = "git"
projects[sarvaka_modules][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_modules.git"

projects[kmaps_navigator][type] = "module"
projects[kmaps_navigator][download][type] = "git"
projects[kmaps_navigator][download][url] = "https://github.com/shanti-uva/drupal_kmaps_navigator.git"

projects[kmaps_admin][type] = "module"
projects[kmaps_admin][download][type] = "git"
projects[kmaps_admin][download][url] = "https://github.com/shanti-uva/drupal_shanti_kmaps_admin.git"

; Themes
projects[sarvaka_bhutan][type] = "theme"
projects[sarvaka_bhutan][download][type] = "git"
projects[sarvaka_bhutan][download][url] = "https://github.com/shanti-uva/shanti_sarvaka_bhutan.git"

projects[shanti_sarvaka][type] = "theme"
projects[shanti_sarvaka][download][type] = "git"
projects[shanti_sarvaka][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_theme.git"


